/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab6P2_DanielElvir;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Consola = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_ID = new javax.swing.JTextField();
        tf_Fabricante = new javax.swing.JTextField();
        tf_Años = new javax.swing.JTextField();
        tf_PrecioConsola = new javax.swing.JTextField();
        tf_ModeloConsola = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Consolas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        cb_TipoConsola = new javax.swing.JComboBox<>();
        JD_Juegos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cb_Consolas = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        tf_Descripcion = new javax.swing.JTextField();
        jdc_Fecha = new com.toedter.calendar.JDateChooser();
        tf_Precio = new javax.swing.JTextField();
        cb_Estado = new javax.swing.JComboBox<>();
        cb_Rentable = new javax.swing.JComboBox<>();
        cb_Agregado = new javax.swing.JComboBox<>();
        sp_Cantidad = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_Juegos = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        cb_JuegosList = new javax.swing.JComboBox<>();
        JD_Estacionario = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_NumeroControles = new javax.swing.JTextField();
        tf_Almacenamiento = new javax.swing.JTextField();
        cb_TipoConexion = new javax.swing.JComboBox<>();
        AgregarEstacionario = new javax.swing.JButton();
        JD_Portatil = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        AgregarPortatil = new javax.swing.JButton();
        cb_TamañoPantalla = new javax.swing.JComboBox<>();
        tf_Bateria = new javax.swing.JTextField();
        cb_Estuche = new javax.swing.JComboBox<>();
        crudTABLA = new javax.swing.JPopupMenu();
        tablaModificar = new javax.swing.JMenuItem();
        tablaEliminar = new javax.swing.JMenuItem();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AgregarConsola = new javax.swing.JButton();
        AgregarJuego = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel5.setText("Agregar Consola");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Identificación");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Fabricante");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Años de Uso");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Precio de la Consola");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Modelo de la Consola");

        jt_Consolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Años de Uso", "Precio ", "Modelo", "Tipo de Consola", "Numero de Controles", "Almacenamiento", "Tipo de Conexion", "Tamaño de Pantalla", "Bateria", "Tiene Estuche?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_Consolas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_ConsolasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Consolas);

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setText("Tipo de Consola");

        cb_TipoConsola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Estacionario", "Portatil" }));
        cb_TipoConsola.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_TipoConsolaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_ID)
                    .addComponent(tf_Fabricante)
                    .addComponent(tf_Años)
                    .addComponent(tf_PrecioConsola)
                    .addComponent(tf_ModeloConsola, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cb_TipoConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(351, 351, 351))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(cb_TipoConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_Fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_Años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_PrecioConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_ModeloConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_ConsolaLayout = new javax.swing.GroupLayout(JD_Consola.getContentPane());
        JD_Consola.getContentPane().setLayout(JD_ConsolaLayout);
        JD_ConsolaLayout.setHorizontalGroup(
            JD_ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ConsolaLayout.setVerticalGroup(
            JD_ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel20.setText("Agregar Juegos");

        jLabel21.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel21.setText("Consola a la cual pertenece:");

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setText("Nombre");

        jLabel23.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel23.setText("Descripcion");

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel24.setText("Fecha de Lanzamiento");

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel25.setText("Precio");

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel26.setText("Estado");

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel27.setText("Es rentable?");

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel28.setText("Tiene Agregado?");

        jLabel29.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel29.setText("Cantidad Disponible");

        cb_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Usado" }));

        cb_Rentable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        cb_Agregado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jButton2.setText("Agregar Juego");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jl_Juegos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_Juegos);

        jLabel30.setText("Juegos de la Consola");

        cb_JuegosList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_JuegosListItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel20)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel26)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_Consolas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_Nombre)
                                .addComponent(tf_Descripcion)
                                .addComponent(jdc_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(tf_Precio)
                                .addComponent(cb_Estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_Rentable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_Agregado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(sp_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cb_JuegosList, 0, 203, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(96, 96, 96))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel30)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cb_Consolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tf_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jdc_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(tf_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(cb_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(cb_Rentable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cb_Agregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(sp_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_JuegosList, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );

        javax.swing.GroupLayout JD_JuegosLayout = new javax.swing.GroupLayout(JD_Juegos.getContentPane());
        JD_Juegos.getContentPane().setLayout(JD_JuegosLayout);
        JD_JuegosLayout.setHorizontalGroup(
            JD_JuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_JuegosLayout.setVerticalGroup(
            JD_JuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setText("Detalles del Estacionario");

        jLabel13.setText("Numero de Controles");

        jLabel14.setText("Almacenamiento");

        jLabel15.setText("Tipo de Conexion");

        cb_TipoConexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HDMI", "TCG", "AV 1", "USB" }));

        AgregarEstacionario.setText("Agregar");
        AgregarEstacionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEstacionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_NumeroControles)
                            .addComponent(tf_Almacenamiento)
                            .addComponent(cb_TipoConexion, 0, 172, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(AgregarEstacionario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_NumeroControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_Almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cb_TipoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(AgregarEstacionario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_EstacionarioLayout = new javax.swing.GroupLayout(JD_Estacionario.getContentPane());
        JD_Estacionario.getContentPane().setLayout(JD_EstacionarioLayout);
        JD_EstacionarioLayout.setHorizontalGroup(
            JD_EstacionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_EstacionarioLayout.setVerticalGroup(
            JD_EstacionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel16.setText("Detalles del Portatil");

        jLabel17.setText("Tamaño de la Pantalla");

        jLabel18.setText("Bateria");

        jLabel19.setText("Tiene Estuche?");

        AgregarPortatil.setText("Agregar Portatil");
        AgregarPortatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPortatilActionPerformed(evt);
            }
        });

        cb_TamañoPantalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));

        cb_Estuche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_TamañoPantalla, 0, 178, Short.MAX_VALUE)
                            .addComponent(tf_Bateria)
                            .addComponent(cb_Estuche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cb_TamañoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb_Estuche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(AgregarPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_PortatilLayout = new javax.swing.GroupLayout(JD_Portatil.getContentPane());
        JD_Portatil.getContentPane().setLayout(JD_PortatilLayout);
        JD_PortatilLayout.setHorizontalGroup(
            JD_PortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_PortatilLayout.setVerticalGroup(
            JD_PortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tablaModificar.setText("Modificar Item");
        crudTABLA.add(tablaModificar);

        tablaEliminar.setText("Eliminar Row");
        tablaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaEliminarActionPerformed(evt);
            }
        });
        crudTABLA.add(tablaEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Bienvenido a la Tienda de Videojuegos y más");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Que desea hacer?");

        AgregarConsola.setBackground(new java.awt.Color(102, 0, 102));
        AgregarConsola.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarConsola.setForeground(new java.awt.Color(255, 255, 255));
        AgregarConsola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Comparación-de-consolas.jpg"))); // NOI18N
        AgregarConsola.setText("Agregar Consola");
        AgregarConsola.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        AgregarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarConsolaActionPerformed(evt);
            }
        });

        AgregarJuego.setBackground(new java.awt.Color(102, 0, 102));
        AgregarJuego.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AgregarJuego.setForeground(new java.awt.Color(255, 255, 255));
        AgregarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rankings-mejores-videojuegos.jpg"))); // NOI18N
        AgregarJuego.setText("Agregar VideoJuego");
        AgregarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarJuegoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Agregar Consola");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Agregar Juego");

        Salir.setBackground(new java.awt.Color(102, 0, 102));
        Salir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Salir.setText("Salir del Sistema");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(AgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(189, 189, 189))
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel2)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(379, 379, 379))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(128, 128, 128)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarConsolaActionPerformed
        JD_Consola.pack();
        JD_Consola.setModal(true);
        JD_Consola.setLocationRelativeTo(this);
        JD_Consola.setVisible(true);
    }//GEN-LAST:event_AgregarConsolaActionPerformed

    private void AgregarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarJuegoActionPerformed
        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) cb_Consolas.getModel();
        for (Consola t : consolas) {
            modelo.addElement(t);
        }

        cb_Consolas.setModel(modelo);

        DefaultComboBoxModel modelo1
                = (DefaultComboBoxModel) cb_JuegosList.getModel();
        for (Consola t : consolas) {
            modelo1.addElement(t);
        }
        cb_JuegosList.setModel(modelo1);
        cb_Consolas.setModel(modelo);
        JD_Juegos.pack();
        JD_Juegos.setModal(true);
        JD_Juegos.setLocationRelativeTo(this);
        JD_Juegos.setVisible(true);
        //cb_Consolas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));

    }//GEN-LAST:event_AgregarJuegoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void cb_TipoConsolaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_TipoConsolaItemStateChanged
        if (cb_TipoConsola.getSelectedItem().equals("Estacionario")) {
            JD_Estacionario.pack();
            JD_Estacionario.setModal(true);
            JD_Estacionario.setLocationRelativeTo(JD_Consola);
            JD_Estacionario.setVisible(true);
        } else if (cb_TipoConsola.getSelectedItem().equals("Portatil")) {
            JD_Portatil.pack();
            JD_Portatil.setModal(true);
            JD_Portatil.setLocationRelativeTo(JD_Consola);
            JD_Portatil.setVisible(true);
        }

    }//GEN-LAST:event_cb_TipoConsolaItemStateChanged

    private void AgregarEstacionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEstacionarioActionPerformed
        try {
            DefaultTableModel modelo = (DefaultTableModel) jt_Consolas.getModel();
            String ID = tf_ID.getText();
            String Fabricante = tf_Fabricante.getText();
            int Años = Integer.parseInt(tf_Años.getText());
            double Precio = Double.parseDouble(tf_PrecioConsola.getText());
            String Modelo = tf_ModeloConsola.getText();
            int Numero_Contoles = Integer.parseInt(tf_NumeroControles.getText());
            int Almacenamiento = Integer.parseInt(tf_Almacenamiento.getText());
            String Tipo_Conexion = cb_TipoConexion.getSelectedItem().toString();
            Estacionaria t = new Estacionaria(Numero_Contoles, Almacenamiento, Tipo_Conexion, ID, Fabricante, Años, Precio, Modelo);
            consolas.add(t);
            try {

                Object[] row = {t.getID(), t.getFabrincante(), t.getAños_Uso(), t.getPrecio(), t.getModelo(), cb_TipoConsola.getSelectedItem().toString(), t.getNumero_Controles(), t.getAlmacenamiento(), t.getTipo_Conexion()};
                modelo.addRow(row);
                jt_Consolas.setModel(modelo);

            } catch (Exception ex) {
                ex.printStackTrace();
            }

            tf_ID.setText("");
            tf_Fabricante.setText("");
            tf_Años.setText("");
            tf_PrecioConsola.setText("");
            tf_ModeloConsola.setText("");
            JD_Estacionario.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JD_Estacionario, "Ocurrió un error");
        }

    }//GEN-LAST:event_AgregarEstacionarioActionPerformed

    private void AgregarPortatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPortatilActionPerformed
        try {
            String ID = tf_ID.getText();
            String Fabricante = tf_Fabricante.getText();
            int Años = Integer.parseInt(tf_Años.getText());
            double Precio = Double.parseDouble(tf_PrecioConsola.getText());
            String Modelo = tf_ModeloConsola.getText();
            String Tamaño_Pantalla = cb_TamañoPantalla.getSelectedItem().toString();
            int Bateria = Integer.parseInt(tf_Bateria.getText());
            boolean estuche = true;
            if (cb_Estuche.getSelectedItem().equals("Si")) {
                estuche = true;
            } else if (cb_Estuche.getSelectedItem().equals("No")) {
                estuche = false;
            }

            Portatil t = new Portatil(Tamaño_Pantalla, Bateria, estuche, ID, Fabricante, Años, Precio, Modelo);
            consolas.add(t);
            try {
                Object[] row = {t.getID(), t.getFabrincante(), t.getAños_Uso(), t.getPrecio(), t.getModelo(), cb_TipoConsola.getSelectedItem().toString(), "", "", "", t.getTamaño_Pantalla(), t.getBateria(), t.isTieneEstuche()};
                DefaultTableModel modelo = (DefaultTableModel) jt_Consolas.getModel();
                modelo.addRow(row);
                jt_Consolas.setModel(modelo);

            } catch (Exception ex) {
                ex.printStackTrace();
            }

            tf_ID.setText("");
            tf_Fabricante.setText("");
            tf_Años.setText("");
            tf_PrecioConsola.setText("");
            tf_ModeloConsola.setText("");
            JD_Portatil.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JD_Estacionario, "Ocurrió un error");
        }

    }//GEN-LAST:event_AgregarPortatilActionPerformed

    private void jt_ConsolasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_ConsolasMouseClicked
        if (evt.isMetaDown()) {
            crudTABLA.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jt_ConsolasMouseClicked

    private void tablaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaEliminarActionPerformed
        int response = JOptionPane.showConfirmDialog(
                JD_Consola,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {

            DefaultTableModel modelo = (DefaultTableModel) jt_Consolas.getModel();
            int rowSelect = jt_Consolas.getSelectedRow();
            modelo.removeRow(rowSelect);
            jt_Consolas.setModel(modelo);
        }
    }//GEN-LAST:event_tablaEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //DefaultListModel modelo
        //      = (DefaultListModel) jl_Juegos.getModel();
        try {
            consolaselec = (Consola) cb_Consolas.getSelectedItem();
            String Nombre = tf_Nombre.getText();
            String Descripcion = tf_Descripcion.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
            Date Fecha = jdc_Fecha.getDate();
            double Precio = Double.parseDouble(tf_Precio.getText());
            String Estado = cb_Estado.getSelectedItem().toString();
            boolean rentable = true;
            if (cb_Rentable.getSelectedItem().equals("Si")) {
                rentable = true;
            } else if (cb_Rentable.getSelectedItem().equals("No")) {
                rentable = false;
            }
            boolean agregado = true;
            if (cb_Agregado.getSelectedItem().equals("Si")) {
                agregado = true;
            } else if (cb_Agregado.getSelectedItem().equals("No")) {
                agregado = false;
            }
            int Cantidad = (int) sp_Cantidad.getValue();
            consolaselec.getJuegos().add(new Juego(Nombre, Descripcion, Fecha, Precio, Estado, rentable, agregado, Cantidad));
            JOptionPane.showMessageDialog(JD_Juegos, "Juego agregado a la consola");
            //modelo.addElement(new Juego(Nombre, Descripcion, Fecha, Precio, Estado, rentable, agregado, Cantidad));
            //jl_Juegos.setModel(modelo);
            tf_Nombre.setText("");
            tf_Descripcion.setText("");
            jdc_Fecha.setDate(new Date());
            tf_Precio.setText("");
            sp_Cantidad.setValue(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(JD_Juegos, "Ocurrió un error");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_JuegosListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_JuegosListItemStateChanged
        DefaultListModel modeloLista = (DefaultListModel) jl_Juegos.getModel();
        modeloLista.removeAllElements();
        consolaselec = (Consola) cb_JuegosList.getSelectedItem();
        modeloLista.addAll(consolaselec.getJuegos());
        jl_Juegos.setModel(modeloLista);

    }//GEN-LAST:event_cb_JuegosListItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    ArrayList<Consola> consolas = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarConsola;
    private javax.swing.JButton AgregarEstacionario;
    private javax.swing.JButton AgregarJuego;
    private javax.swing.JButton AgregarPortatil;
    private javax.swing.JDialog JD_Consola;
    private javax.swing.JDialog JD_Estacionario;
    private javax.swing.JDialog JD_Juegos;
    private javax.swing.JDialog JD_Portatil;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> cb_Agregado;
    private javax.swing.JComboBox<String> cb_Consolas;
    private javax.swing.JComboBox<String> cb_Estado;
    private javax.swing.JComboBox<String> cb_Estuche;
    private javax.swing.JComboBox<String> cb_JuegosList;
    private javax.swing.JComboBox<String> cb_Rentable;
    private javax.swing.JComboBox<String> cb_TamañoPantalla;
    private javax.swing.JComboBox<String> cb_TipoConexion;
    private javax.swing.JComboBox<String> cb_TipoConsola;
    private javax.swing.JPopupMenu crudTABLA;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdc_Fecha;
    private javax.swing.JList<String> jl_Juegos;
    private javax.swing.JTable jt_Consolas;
    private javax.swing.JSpinner sp_Cantidad;
    private javax.swing.JMenuItem tablaEliminar;
    private javax.swing.JMenuItem tablaModificar;
    private javax.swing.JTextField tf_Almacenamiento;
    private javax.swing.JTextField tf_Años;
    private javax.swing.JTextField tf_Bateria;
    private javax.swing.JTextField tf_Descripcion;
    private javax.swing.JTextField tf_Fabricante;
    private javax.swing.JTextField tf_ID;
    private javax.swing.JTextField tf_ModeloConsola;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_NumeroControles;
    private javax.swing.JTextField tf_Precio;
    private javax.swing.JTextField tf_PrecioConsola;
    // End of variables declaration//GEN-END:variables
    private Consola consolaselec;
}
